### ISSUE TITLE
Unable to parse dictonary of day2 exercise EOF is missing 

### ISSUE THREAD

**Issue by som-kanade** [LetusDevops/LearnPython#2]
This is the corrected dictonary the issue was on last line of enemies 

a_dict = [
    {
        "name": "gara",
        "power": "some sand related jutsu",
        "powerlevel": 199,
        "frieds": [
            {
                "name": "Naruto",
                "friend_points": 28,
                "enemies": ["Saitama"] 
            },
            {
                "name": "Boruto",
                "friend_points": 18,
                "enemies": ["Saitama"]
            }
        ]
    },
    {
        "name": "Alex",
        "power": "some titans powers",
        "powerlevel": 1199,
        "frieds": [
            {
            "name": "Soniya",
            "friend_points": 128,
            "enemies": ["Saitama"] 
            }
        ]
    },
    {
        "name": "King",
        "power": "some titans powers",
        "powerlevel": 1199,
        "frieds": [
            {
            "name": "Saitama",
            "friend_points": 128,
             **"enemies": ["Naruto", "gara", "boruto]**  >> original 
            **"enemies": ["Naruto", "gara", "boruto"]** >> fixed
            }
        ]
    }
]

**Comment by chowmean** [comment]
Fixed.
